name: flutter_mvvm_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  get_it: ^9.0.5
  go_router: ^16.3.0
  logger: ^2.6.2
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
